Convert input embeddings into key,query, value vectors

In [3]:
import torch

inputs_posttrained = torch.tensor([ [0.44, 0.15, 0.89], #Your
                                    [0.55, 0.87, 0.66], #journey
                                    [0.53, 0.85, 0.67], #starts
                                    [0.22, 0.58, 0.33], #with
                                    [0.77, 0.25, 0.10], #one
                                    [0.05, 0.80, 0.55]])  #step



In [8]:
# for the word journey
x_2 = inputs_posttrained[1]

# fixed size of all the weight matrices (query, key. value) will be 3 x 2
dim_in = inputs_posttrained.shape[1]

dim_out = 2

In [10]:
torch.manual_seed(42)

W_query = torch.nn.Parameter(torch.rand(dim_in,dim_out) , requires_grad=False)

W_key = torch.nn.Parameter(torch.rand(dim_in,dim_out) , requires_grad=False)

W_value = torch.nn.Parameter(torch.rand(dim_in,dim_out) , requires_grad=False)

print("Query:", W_query )
      
print("\nKey:", W_key)

print("\nValue:", W_value)


Query: Parameter containing:
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

Key: Parameter containing:
tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

Value: Parameter containing:
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])
